### ISSUE TITLE
SequenceIdGenerator not able to start in version 3.2.1.51.14

### ISSUE THREAD

**Issue by joehmchan** [graphaware/neo4j-uuid#42]
I am not able to set uuidGeneratorClass as SequenceIdGenerator, with latest version 3.2.1.51.14.
I am using Neo4j 3.2.1.

This is my neo4j.conf
```
# GraphAware Framework
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware

# GraphAware Sequence Id generator
com.graphaware.runtime.enabled=true
com.graphaware.module.UUID.1=com.graphaware.module.uuid.UuidBootstrapper
com.graphaware.module.UUID.relationship=com.graphaware.runtime.policy.all.IncludeAllBusinessRelationships
com.graphaware.module.UUID.uuidProperty=sequence
com.graphaware.module.UUID.uuidGeneratorClass=com.graphaware.module.uuid.generator.SequenceIdGenerator
```

Here is my docker message
```
neo4j | 2017-06-21 03:50:01.408+0000 INFO  ======== Neo4j 3.2.1 ========
neo4j | 2017-06-21 03:50:01.786+0000 INFO  Starting...
neo4j | 2017-06-21 03:50:02.778+0000 INFO  Bolt enabled on 0.0.0.0:7687.
neo4j | 2017-06-21 03:50:04.212+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
neo4j | 2017-06-21 03:50:04.244+0000 WARN  Topology change adapter is not available on community edition
neo4j | 2017-06-21 03:50:04.246+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 1, ID UUID, using com.graphaware.module.uuid.UuidBootstrapper
neo4j | 2017-06-21 03:50:04.338+0000 INFO  Relationship Inclusion Policy set to com.graphaware.common.policy.inclusion.composite.CompositeRelationshipInclusionPolicy@e4890241
neo4j | 2017-06-21 03:50:04.339+0000 INFO  uuidProperty set to sequence
neo4j | 2017-06-21 03:50:04.339+0000 INFO  uuidGenerator set to com.graphaware.module.uuid.generator.SequenceIdGeneratorwrapper.java.additional=-Dneo4j.ext.udc.source=docker
neo4j | 2017-06-21 03:50:04.351+0000 ERROR [c.g.r.b.RuntimeKernelExtension] Unable to bootstrap module 1 Unable to instantiate UuidGenerator of type 'com.graphaware.module.uuid.generator.SequenceIdGeneratorwrapper.java.additional=-Dneo4j.ext.udc.source=docker'
neo4j | java.lang.RuntimeException: Unable to instantiate UuidGenerator of type 'com.graphaware.module.uuid.generator.SequenceIdGeneratorwrapper.java.additional=-Dneo4j.ext.udc.source=docker'
neo4j |     at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
neo4j |     at com.graphaware.module.uuid.UuidModule.instantiateUuidGenerator(UuidModule.java:68)
neo4j |     ... 21 more
neo4j | 2017-06-21 03:50:04.352+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
neo4j | 2017-06-21 03:50:10.583+0000 INFO  Starting GraphAware...
neo4j | 2017-06-21 03:50:10.583+0000 INFO  Loading module metadata...
neo4j | 2017-06-21 03:50:10.622+0000 INFO  Module metadata loaded.
neo4j | 2017-06-21 03:50:10.622+0000 INFO  Starting transaction-driven modules...
neo4j | 2017-06-21 03:50:10.622+0000 INFO  Transaction-driven modules started.
neo4j | 2017-06-21 03:50:10.623+0000 INFO  There are no timer-driven runtime modules. Not scheduling any tasks.
neo4j | 2017-06-21 03:50:10.623+0000 INFO  GraphAware started.
neo4j | 2017-06-21 03:50:10.623+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime automatically started.
neo4j | 2017-06-21 03:50:12.927+0000 INFO  Started.
neo4j | 2017-06-21 03:50:13.239+0000 INFO [c.g.s.f.b.GraphAwareServerBootstrapper] started
neo4j | 2017-06-21 03:50:13.250+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
neo4j | 2017-06-21 03:50:13.511+0000 INFO  Google Analytics disabled
neo4j | 2017-06-21 03:50:13.544+0000 INFO  Mounting GraphAware Framework at /graphaware
neo4j | 2017-06-21 03:50:13.567+0000 INFO  Will try to scan the following packages: {com.**.graphaware.**,org.**.graphaware.**,net.**.graphaware.**}
neo4j | 2017-06-21 03:50:16.487+0000 INFO  Remote interface available at http://localhost:7474/
```

**Comment by bachmanm** [comment]
where does the `.java.additional=-Dneo4j.ext.udc.source=docker` come from? That should not be there... Let us investigate

**Comment by joehmchan** [comment]
Is it because I am running it as docker?

**Comment by ikwattro** [comment]
Can you paste your full neo4j config, seems to me that a line break is missing somehow

**Comment by joehmchan** [comment]
[neo4j.conf.txt](https://github.com/graphaware/neo4j-uuid/files/1091669/neo4j.conf.txt)
please remove txt extension

**Comment by szenyo** [comment]
@joehmchan  I think you should try first to insert an enter at the end of the last line of neo4j.conf

**Comment by joehmchan** [comment]
It works! Thanks a lot!
