### ISSUE TITLE
Exception in thread "GraphAware Starter" when initializing UIDM module for the first time

### ISSUE THREAD

**Issue by DurkoMatko** [graphaware/neo4j-uuid#62]
Im trying to use GraphAware Neo4j UUID plugin in the following environment:
- OS: Ubuntu 18.04
- Neo4J : neo4j-community-3.5.9
- Java: 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

I've pasted these JARs to the plugins Neo4j folder:

- graphaware-server-all-3.5.14.55.jar
 - uuid-3.5.14.55.19.jar

After runing bin\neo4j console I'm getting this error:

```
2020-09-24 05:39:50.217+0000 INFO  GraphAware Runtime enabled, bootstrapping...
2020-09-24 05:39:50.251+0000 INFO  Bootstrapping module with order 1, ID UIDM, using com.graphaware.module.uuid.UuidBootstrapper
2020-09-24 05:39:50.345+0000 INFO  uuidProperty set to uuid
2020-09-24 05:39:50.345+0000 INFO  stripHyphens set to false
2020-09-24 05:39:50.354+0000 INFO  Registering module UIDM with GraphAware Runtime.
2020-09-24 05:39:50.357+0000 INFO  GraphAware Runtime bootstrapped, starting the Runtime...
2020-09-24 05:39:50.475+0000 INFO  Starting GraphAware...
2020-09-24 05:39:50.482+0000 INFO  Loading module metadata...
2020-09-24 05:39:50.483+0000 INFO  Loading metadata for module UIDM
2020-09-24 05:39:50.569+0000 INFO  Module UIDM seems to have been registered for the first time.
2020-09-24 05:39:50.569+0000 INFO  Module UIDM seems to have been registered for the first time, will try to initialize...
2020-09-24 05:39:50.574+0000 INFO  InitializeUntil set to 9223372036854775807 and it is 1600925990574. Will initialize.
2020-09-24 05:39:50.712+0000 WARN  Waited for over 100ms but no input arrived. Still expecting more input. 
Exception in thread "GraphAware Starter" java.lang.NoClassDefFoundError: org/omg/CORBA/portable/IDLEntity
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.graphaware.common.uuid.EaioUuidGenerator.generateUuid(EaioUuidGenerator.java:31)
	at com.graphaware.module.uuid.UuidModule.assignNewUuid(UuidModule.java:192)
	at com.graphaware.module.uuid.UuidModule.assignUuid(UuidModule.java:183)
	at com.graphaware.module.uuid.UuidModule.lambda$initialize$0(UuidModule.java:107)
	at com.graphaware.tx.executor.batch.IterableInputBatchTransactionExecutor.lambda$processQueue$1(IterableInputBatchTransactionExecutor.java:115)
	at com.graphaware.tx.executor.single.SimpleTransactionExecutor.doExecuteInTransaction(SimpleTransactionExecutor.java:69)
	at com.graphaware.tx.executor.single.SimpleTransactionExecutor.executeInTransaction(SimpleTransactionExecutor.java:58)
	at com.graphaware.tx.executor.batch.IterableInputBatchTransactionExecutor.processQueue(IterableInputBatchTransactionExecutor.java:103)
	at com.graphaware.tx.executor.batch.IterableInputBatchTransactionExecutor.doExecute(IterableInputBatchTransactionExecutor.java:76)
	at com.graphaware.tx.executor.batch.DisposableBatchTransactionExecutor.execute(DisposableBatchTransactionExecutor.java:35)
	at com.graphaware.module.uuid.UuidModule.initialize(UuidModule.java:110)
	at com.graphaware.runtime.manager.ProductionTxDrivenModuleManager.initialize(ProductionTxDrivenModuleManager.java:57)
	at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.initializeIfAllowed(BaseTxDrivenModuleManager.java:128)
	at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.handleNoMetadata(BaseTxDrivenModuleManager.java:72)
	at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.handleNoMetadata(BaseTxDrivenModuleManager.java:39)
	at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:143)
	at com.graphaware.runtime.manager.BaseModuleManager.loadMetadata(BaseModuleManager.java:125)
	at com.graphaware.runtime.TxDrivenRuntime.loadMetadata(TxDrivenRuntime.java:130)
	at com.graphaware.runtime.ProductionRuntime.loadMetadata(ProductionRuntime.java:80)
	at com.graphaware.runtime.BaseGraphAwareRuntime.startModules(BaseGraphAwareRuntime.java:154)
	at com.graphaware.runtime.TxDrivenRuntime.startModules(TxDrivenRuntime.java:146)
	at com.graphaware.runtime.ProductionRuntime.startModules(ProductionRuntime.java:70)
	at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:134)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.lambda$start$0(RuntimeKernelExtension.java:117)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.IDLEntity
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 34 more
```

Has someone pls any idea? I've followed the steps in the[ Readme Setup](https://github.com/graphaware/neo4j-uuid#setup-and-configuration) section. Thx!

**Comment by Marc-Roth** [comment]
I'm receiving the same error on a debian server having almost the same setup.
Any news about it?

**Comment by Tak1za** [comment]
Did anyone find a resolution?

**Comment by Tak1za** [comment]
I found a fix for this:
Downloading the jar from here: https://repo1.maven.org/maven2/org/ow2/jonas/osgi/corba-api/5.0.1/
And putting it inside the plugins folder seems to fix the issue.
